---
# Keep build, deployment, and ANTA artifacts relative to the root playbooks.
root_dir: "{{ playbook_dir }}"
ansible_user: arista
ansible_password: admin
ansible_network_os: arista.eos.eos
# Configure privilege escalation
ansible_become: true
ansible_become_method: enable
ansible_connection: httpapi
ansible_httpapi_port: 443
ansible_httpapi_use_ssl: true
ansible_httpapi_validate_certs: false
ansible_python_interpreter: $(which python3)

aaa_settings:
  authorization:
    exec:
      default: local
  local_users:
    - name: arista
      privilege: 15
      role: network-admin
      cleartext_password: "{{ ansible_password }}"

mgmt_gateway: 192.0.2.1
mgmt_interface_settings:
  vrf: MGMT

management_eapi:
  enabled: true
